### PR TITLE
Upgrade to middleman 4

### PR DESCRIPTION
**Pull request by PotHix**
This is a big PR. I managed to update middleman to its latest version, so we can now use the latest ruby and libs and also stop using unmaintained ones.

Here is what I had to do:

* change `index.md` to `index.html.md` in order to get proper file
  generation
* remove compass, as it's not maintained for a while
* include the right CSS files with the proper file extensions (scss)
* bump all other gems related to it
* update javascripts using slate theme

We also updated the ruby version, it now works with (but not limited to) ruby 2.4.1

Please check if there was any feature that I don't know and it's now missing.

### CODE REVIEW

**Comment by lefcha** [comment]
Great work! 👍 

It would be great if we have the same dependencies as the https://github.com/Doist/Twist-API, if possible, instead of installing new dependencies or different versions.

Also, I managed to build it and run it, and the `shell` and `python` buttons don't work.

May I suggest that we rebase everything on the same version of the slate template we use for the Twist-API, and just move our `.md` files there, and only add our cosmetic CSS changes and the top bar?

What do you think Roman?

**Comment by PotHix** [comment]
@lefcha @imankulov Built it again from scratch using the latest version of Slate.
In case you like it, I intend to apply this template to the other docs.

**Comment by PotHix** [comment]
BTW, don't worry about travis, I'm still working on it.

**Comment by PotHix** [comment]
Travis is ok now :D

**Comment by lefcha** [comment]
Everything looks good to me now 👍 Well done!

**Pull request merged**
